services:
    backend:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: creds-api
        restart: unless-stopped
        networks:
            - dashboard
        volumes:
            - app_data:/data

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        container_name: creds-ui
        restart: unless-stopped
        networks:
            - dashboard
        depends_on:
            - backend

volumes:
    app_data:

networks:
    dashboard:
        external: true