services:
    backend:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: creds-api
        restart: unless-stopped
        networks:
            - dashboard
        environment:
            - MONGODB_URI=mongodb://mongo:27017/
            - DB_NAME=CredentialManager

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        container_name: creds-ui
        restart: unless-stopped
        networks:
            - dashboard
        depends_on:
            - backend

networks:
    dashboard:
        external: true
